name: mu_scaling_system
description: Make your design adaptive for all screens using mu system
version: 0.1.0
homepage: https://pub.dev/packages/mu_scaling_system
repository: https://github.com/meg4cyberc4t/mu_scaling_system

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

